version: '3.1'
services:
  db:
    image: mariadb:10.7.3
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 20
    env_file:
      - .env.docker.production.api
  api:
    image: ownrecipes/ownrecipes-api
    command: /startup/prod-entrypoint.sh
    restart: on-failure
    volumes:
      - static-files:/code/static-files
      - site-media:/code/site-media
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker.production.api
  web:
    image: ownrecipes/ownrecipes-web
    volumes:
      - public-ui:/code/public-ui
    env_file:
      - .env.docker.production.web
  nginx:
    image: ownrecipes/ownrecipes-nginx
    command: ./start.sh
    volumes:
      - static-files:/var/www/html/ownrecipes-static/static-files
      - site-media:/var/www/html/ownrecipes-static/site-media
      - public-ui:/var/www/html/ownrecipes-static/public-ui
      # - /opt/ownrecipes/ssl:/ssl/:ro
    depends_on:
      - api
      - web
    env_file:
      - .env.docker.production.api
volumes:
  database:
  public-ui:
  static-files:
  site-media:
